import os

# INFRASTRUCTURE
#  OLLAMA_HOST = os.getenv("OLLAMA_HOST", "localhost"); print(OLLAMA_HOST)
OLLAMA_URL = "http://host.docker.internal:11434/api/generate"
MODEL_NAME = "llama3"

# UI AESTHETICS (NOCTILUCENT THEME)
PAGE_TITLE = "Noctilucent Intelligence Suite"
PAGE_LAYOUT = "wide"

# Colors (Hex)
COLOR_BG_PRIMARY = "#000C18"      # Deep Midnight Blue
COLOR_BG_SECONDARY = "#001A33"    # Lighter gradient fade
COLOR_TEXT_MAIN = "#E0E0E0"       # High-contrast off-white
COLOR_ACCENT_PLATINUM = "#E2E8F0" # Sleek silver for text/sliders
COLOR_ACCENT_CYAN = "#00E5FF"     # Technical highlights
COLOR_DANGER_RED = "#FF3333"      # Critical thresholds
COLOR_WARN_AMBER = "#FFA500"      # Anomaly markers

# Typography
FONT_MAIN = "'Inter', sans-serif"
FONT_MONO = "'JetBrains Mono', monospace"

# BUSINESS LOGIC & THRESHOLDS
THRESHOLD_CRITICAL = 3.5          # Critical Vacuum Pressure (Pa)
BASELINE_DEFAULT = 0.9            # Standard Operating Pressure (Pa)
DRIFT_TOLERANCE = 0.15            # 15% deviation triggers a drift warning
YIELD_SCRAP_COEF = 12.5           # Wafers scrapped per Pascal over threshold
WAFER_UNIT_COST = 500             # Estimated dollar value per scrapped unit

# SIMULATION LIMITS
LOG_LENGTH_MIN = 10
LOG_LENGTH_MAX = 200
LOG_LENGTH_DEFAULT = 10

SEVERITY_MIN = 1
SEVERITY_MAX = 10
SEVERITY_DEFAULT = 7

BATCH_SIZE_MAX_DISPLAY = 10

# TEXT & LABELS
TITLE_COVER = "00 - SYSTEM INITIALIZATION"
TITLE_SIMULATION = "01 - SIMULATION ENGINE"
TITLE_DASHBOARD = "02 - FACTORY DASHBOARD"
TITLE_COPILOT = "FACTORY AI COPILOT"

# --- SEMICONDUCTOR KNOWLEDGE BASE ---
SEMICONDUCTOR_FACTS = [
    "Photolithography can achieve features smaller than 10 nm.",
    "Silicon wafers are typically 300 mm in diameter.",
    "Cleanrooms used in fabs are cleaner than operating rooms.",
    "Extreme ultraviolet (EUV) lithography uses 13.5 nm wavelength light.",
    "Transistors are built layer by layer using deposition and etching.",
    "Moore's Law predicted transistor density doubling every ~2 years.",
    "Modern chips can contain tens of billions of transistors.",
    "Ion implantation is used to dope semiconductors precisely.",
    "Chemical mechanical polishing (CMP) smooths wafer surfaces.",
    "Silicon is the most widely used semiconductor material.",
    "Gallium nitride (GaN) is used for high-power applications.",
    "Silicon carbide (SiC) is used in electric vehicle power systems.",
    "Fabs cost billions of dollars to build.",
    "A single dust particle can ruin a chip.",
    "Photoresist materials react to light to define patterns.",
    "Deposition techniques include CVD and PVD.",
    "Etching can be wet or dry (plasma-based).",
    "Cleanroom workers wear full-body suits called bunny suits.",
    "Semiconductor fabs run 24/7.",
    "Yield refers to the percentage of functional chips per wafer.",
    "Defect density is critical for manufacturing success.",
    "Metrology tools measure nanoscale features.",
    "Process nodes like 7 nm or 5 nm refer to scaling generations.",
    "FinFET transistors improved leakage and performance.",
    "GAAFET is the next transistor evolution after FinFET.",
    "Mask sets can cost millions of dollars.",
    "Photomasks define circuit patterns.",
    "Overlay accuracy is critical in multi-layer fabrication.",
    "Annealing repairs crystal damage after implantation.",
    "Oxidation creates insulating silicon dioxide layers.",
    "Interconnects are often made of copper.",
    "Low-k dielectrics reduce capacitance in interconnects.",
    "Air gaps can be used to reduce capacitance further.",
    "Wafer thinning is used in advanced packaging.",
    "Backside processing enables new device architectures.",
    "3D stacking increases chip density.",
    "Through-silicon vias (TSVs) connect stacked dies.",
    "Advanced packaging includes chiplets and interposers.",
    "Chiplets allow modular chip design.",
    "Testing happens at wafer level and after packaging.",
    "Burn-in testing stresses chips to detect early failures.",
    "Electromigration affects long-term reliability.",
    "Thermal management is critical for performance.",
    "Power density increases with scaling.",
    "Clock speeds are limited by heat dissipation.",
    "Yield learning improves over time.",
    "Statistical process control is essential in fabs.",
    "Automation is heavily used in fabs.",
    "Robots transport wafers between tools.",
    "FOUPs (Front Opening Unified Pods) carry wafers.",
    "Vacuum environments are used in many processes.",
    "Plasma is used in etching and deposition.",
    "Atomic layer deposition (ALD) enables precise thin films.",
    "ALD can deposit one atomic layer at a time.",
    "Gate oxides are only a few atoms thick.",
    "Leakage currents increase as devices shrink.",
    "High-k materials replaced SiO2 in gate dielectrics.",
    "Metal gates replaced polysilicon gates.",
    "Strained silicon improves carrier mobility.",
    "Epitaxy grows crystalline layers on wafers.",
    "Defects can be point, line, or planar.",
    "Wafer inspection uses optical and electron methods.",
    "SEM and TEM provide nanoscale imaging.",
    "Process integration combines multiple steps.",
    "Each wafer goes through hundreds of steps.",
    "Cycle time for a wafer can be weeks.",
    "Fabs use enormous amounts of water.",
    "Ultra-pure water is essential for cleaning.",
    "Chemical purity must be extremely high.",
    "Process recipes are tightly controlled.",
    "Temperature control is critical in many steps.",
    "Vacuum pumps are essential for many tools.",
    "Photolithography requires alignment accuracy of nanometers.",
    "Reticles are used in lithography systems.",
    "Stepper machines expose one die at a time.",
    "Scanner machines use moving exposure.",
    "EUV systems are extremely complex and expensive.",
    "EUV uses reflective optics instead of lenses.",
    "Pellicles protect photomasks from contamination.",
    "Line edge roughness affects device performance.",
    "Critical dimension (CD) control is essential.",
    "Process nodes are marketing terms more than physical dimensions.",
    "Back-end-of-line (BEOL) forms interconnects.",
    "Front-end-of-line (FEOL) forms transistors.",
    "Middle-of-line (MOL) connects transistors to interconnects.",
    "Dielectric layers isolate metal layers.",
    "Multiple patterning extends lithography capabilities.",
    "Self-aligned double patterning (SADP) improves resolution.",
    "Self-aligned quadruple patterning (SAQP) further improves scaling.",
    "Wafer bonding is used in 3D integration.",
    "Hybrid bonding enables high-density interconnects.",
    "Flip-chip packaging improves performance.",
    "Wire bonding is an older packaging method.",
    "Ball grid arrays (BGA) are common packages.",
    "Thermal vias help dissipate heat.",
    "Heat spreaders distribute heat across chips.",
    "Chip packaging impacts signal integrity.",
    "Signal delay increases with interconnect length.",
    "RC delay is a major limitation in scaling.",
    "Design rules define layout constraints.",
    "EDA tools automate chip design.",
    "Verification ensures design correctness.",
    "Tape-out marks the final design submission.",
    "Mask fabrication follows tape-out.",
    "Yield ramp is critical after new node introduction.",
    "Fabs use statistical models to predict yield.",
    "Redundancy can improve yield.",
    "Spare rows/columns are used in memory chips.",
    "DRAM and NAND flash use different architectures.",
    "NAND flash uses floating gate or charge trap cells.",
    "DRAM requires periodic refresh.",
    "Logic chips differ from memory chips in fabrication.",
    "Analog and digital processes have different requirements.",
    "RF chips require special design considerations.",
    "Power devices prioritize efficiency over density.",
    "Wide bandgap materials enable higher voltages.",
    "Device scaling faces quantum effects.",
    "Quantum tunneling increases leakage.",
    "Short-channel effects degrade transistor control.",
    "Gate-all-around structures improve control.",
    "Nanowires are used in advanced transistors.",
    "Nanosheets are another GAAFET implementation.",
    "Device variability increases at small nodes.",
    "Process corners define performance extremes.",
    "Monte Carlo simulations model variability.",
    "Thermal budgets limit process temperatures.",
    "Diffusion spreads dopants in silicon.",
    "Rapid thermal processing is used for annealing.",
    "Silicides reduce contact resistance.",
    "Contact resistance is critical in scaling.",
    "Metal layers can exceed 10 in modern chips.",
    "Routing congestion is a design challenge.",
    "Power delivery networks must be robust.",
    "IR drop affects circuit performance.",
    "Decoupling capacitors stabilize voltage.",
    "Clock distribution networks must be precise.",
    "Jitter affects timing accuracy.",
    "Timing closure is a major design challenge.",
    "Parasitics impact circuit behavior.",
    "Extraction tools model parasitic effects.",
    "Chip reliability testing includes HTOL.",
    "Electrostatic discharge (ESD) protection is essential.",
    "Latch-up is a failure mode in CMOS.",
    "Guard rings prevent latch-up.",
    "Isolation techniques include STI.",
    "Shallow trench isolation replaces LOCOS.",
    "LOCOS was an older isolation method.",
    "Silicon-on-insulator (SOI) reduces parasitics.",
    "FD-SOI improves low-power performance.",
    "Bulk CMOS is still widely used.",
    "Process development takes years.",
    "Foundries manufacture chips for fabless companies.",
    "IDMs design and manufacture their own chips.",
    "Fabless companies focus on design only.",
    "Design kits (PDKs) define process rules.",
    "PDKs include models for simulation.",
    "Process nodes are labeled like N5, N3, etc.",
    "Wafer scrap is costly in fabs.",
    "Cycle yield affects overall throughput.",
    "Tool downtime impacts production efficiency.",
    "Predictive maintenance reduces downtime.",
    "AI is increasingly used in fabs.",
    "Machine learning improves defect detection.",
    "Digital twins simulate fab processes.",
    "Supply chains for semiconductors are global.",
    "Geopolitics affects chip manufacturing.",
    "Export controls impact advanced technology access.",
    "Fabs require stable power supplies.",
    "Power outages can ruin wafers.",
    "Backup systems are critical in fabs.",
    "Environmental controls maintain humidity and temperature.",
    "Vibration control is essential for lithography.",
    "Cleanroom classifications include ISO standards.",
    "ISO 1 cleanrooms have extremely low particle counts.",
    "Particles are measured per cubic meter.",
    "Airflow is typically laminar in cleanrooms.",
    "HEPA filters remove contaminants.",
    "Chemical filters remove airborne molecules.",
    "Operators undergo strict training.",
    "Process engineers optimize fabrication steps.",
    "Yield engineers analyze defects.",
    "Equipment engineers maintain tools.",
    "Lithography engineers focus on patterning.",
    "Etch engineers optimize plasma processes.",
    "Deposition engineers manage thin films.",
    "Integration engineers coordinate processes.",
    "Process control engineers monitor variability.",
    "Fab managers oversee production.",
    "Wafer maps show defect locations.",
    "Hotspots indicate recurring issues.",
    "Root cause analysis identifies problems.",
    "Corrective actions improve yield.",
    "Continuous improvement is essential.",
    "Kaizen principles are applied in fabs.",
    "Lean manufacturing reduces waste.",
    "Six Sigma improves process quality.",
    "SPC charts monitor process stability.",
    "Control limits define acceptable variation.",
    "Out-of-control signals trigger investigation.",
    "Process drift must be corrected quickly.",
    "Recipe tuning optimizes results.",
    "Equipment calibration ensures accuracy.",
    "Metrology feedback loops improve control.",
    "Overlay errors can cause device failure.",
    "Alignment marks are used for lithography.",
    "Stepper lenses are extremely precise.",
    "EUV mirrors require atomic-level smoothness.",
    "Reflectivity of EUV mirrors is limited.",
    "Vacuum is required for EUV lithography.",
    "EUV sources use plasma generated by lasers.",
    "Tin droplets are used in EUV sources.",
    "Collector optics focus EUV light.",
    "EUV throughput is a major challenge.",
    "Pellicle durability is critical.",
    "Resist sensitivity affects exposure.",
    "Line width roughness affects performance.",
    "Stochastic defects are an issue in EUV.",
    "Process windows define acceptable variations.",
    "Design-technology co-optimization improves results.",
    "Chip scaling slows at advanced nodes.",
    "Chiplet architectures mitigate scaling limits.",
    "Heterogeneous integration combines different technologies.",
    "Optical interconnects may replace electrical ones.",
    "Photonics integration is emerging.",
    "Silicon photonics enables optical communication.",
    "Quantum computing uses different fabrication techniques.",
    "Superconducting qubits require cryogenic environments.",
    "MEMS devices are fabricated using similar processes.",
    "Sensors are a major semiconductor application.",
    "Image sensors use specialized processes.",
    "CMOS sensors dominate camera technology.",
    "Backside illumination improves sensor sensitivity.",
    "Color filters are added to image sensors.",
    "Micro-lenses improve light collection.",
    "Automotive chips require high reliability.",
    "AEC-Q100 defines automotive standards.",
    "Radiation hardening is needed for space chips.",
    "Single-event upsets affect electronics in space.",
    "Shielding and design mitigate radiation effects.",
    "EDA tools simulate radiation effects.",
    "Packaging for space differs from consumer chips.",
    "Chip testing includes functional and parametric tests.",
    "Probe cards test wafers before dicing.",
    "Dicing cuts wafers into individual dies.",
    "Sawing or laser cutting is used.",
    "Pick-and-place machines assemble packages.",
    "Encapsulation protects chips from environment.",
    "Underfill improves mechanical stability.",
    "Thermal cycling tests reliability.",
    "Mechanical stress can cause failure.",
    "Delamination is a packaging issue.",
    "Moisture sensitivity levels define handling requirements.",
    "Baking removes moisture before reflow.",
    "Reflow soldering attaches packages to boards.",
    "Surface mount technology dominates PCB assembly.",
    "Through-hole technology is less common now.",
    "Chip-scale packages reduce size.",
    "Fan-out wafer-level packaging improves performance.",
    "Redistribution layers reroute connections.",
    "Micro-bumps connect dies in advanced packages.",
    "Thermal interface materials improve heat transfer.",
    "Heat sinks dissipate heat.",
    "Active cooling may be required for high-performance chips.",
    "Liquid cooling is used in data centers.",
    "Data center chips prioritize efficiency.",
    "Mobile chips prioritize power consumption.",
    "AI chips require high parallelism.",
    "GPUs are widely used for AI workloads.",
    "ASICs are optimized for specific tasks.",
    "FPGAs offer flexibility.",
    "Reconfigurable logic enables rapid prototyping.",
    "Verification complexity increases with chip size.",
    "Formal verification ensures correctness.",
    "Simulation tests design behavior.",
    "Hardware emulation speeds up testing.",
    "Prototyping uses FPGA platforms.",
    "Time-to-market is critical in semiconductor industry.",
    "First-pass success reduces costs.",
    "Respins are expensive.",
    "Mask changes require new fabrication runs.",
    "Engineering change orders modify designs.",
    "Silicon validation confirms real-world performance.",
    "Debugging silicon is complex.",
    "Failure analysis identifies root causes.",
    "Decapsulation exposes die for inspection.",
    "Cross-sectioning reveals internal structures.",
    "Focused ion beam (FIB) enables modification.",
    "FIB can cut and deposit materials.",
    "Reverse engineering analyzes competitor chips.",
    "Chip security prevents tampering.",
    "Hardware trojans are a concern.",
    "Secure enclaves protect sensitive data.",
    "Encryption engines are built into chips.",
    "Side-channel attacks exploit physical leakage.",
    "Power analysis can reveal secrets.",
    "Design techniques mitigate side-channel risks.",
    "Trusted foundry programs ensure security.",
    "Supply chain integrity is critical.",
    "Chip shortages impact global economy.",
    "Semiconductors are foundational to modern technology.",
    "Every electronic device relies on semiconductors.",
    "Scaling challenges drive innovation.",
    "New materials are being explored.",
    "2D materials like graphene are researched.",
    "Transition metal dichalcogenides are promising.",
    "Spintronics uses electron spin.",
    "Neuromorphic computing mimics the brain.",
    "Memristors enable new architectures.",
    "Phase-change memory stores data differently.",
    "Resistive RAM is another emerging technology.",
    "Ferroelectric memory offers low power.",
    "3D NAND stacks memory cells vertically.",
    "NAND layers exceed 200 in modern devices.",
    "Charge trap flash improves reliability.",
    "Error correction codes improve data integrity.",
    "Wear leveling extends flash lifespan.",
    "Bad block management handles defects.",
    "Controllers manage flash memory operations.",
    "Firmware is critical in storage devices.",
    "SSD performance depends on controller design.",
    "PCIe interfaces enable high-speed data transfer.",
    "NVMe protocol improves storage performance.",
    "Latency is critical in memory systems.",
    "Cache hierarchies improve speed.",
    "SRAM is faster but larger than DRAM.",
    "Embedded memory is integrated into logic chips.",
    "Design trade-offs balance speed, power, and area.",
    "PPA stands for power, performance, area.",
    "Optimization focuses on PPA.",
    "Voltage scaling reduces power consumption.",
    "Dynamic voltage and frequency scaling (DVFS) saves energy.",
    "Leakage power becomes dominant at small nodes.",
    "Power gating reduces leakage.",
    "Clock gating reduces dynamic power.",
    "Thermal design power (TDP) defines cooling needs.",
    "Chip binning sorts chips by performance.",
    "Overclocking increases performance at higher power.",
    "Undervolting reduces power consumption.",
    "Reliability degrades over time.",
    "Aging mechanisms include BTI and HCI.",
    "BTI stands for bias temperature instability.",
    "HCI stands for hot carrier injection.",
    "Design margins account for aging.",
    "Redundancy improves fault tolerance.",
    "ECC memory corrects errors.",
    "Parity bits detect errors.",
    "System-level design considers chip behavior.",
    "SoCs integrate multiple components.",
    "Integration reduces latency and power.",
    "Heterogeneous computing combines different cores.",
    "ARM architectures dominate mobile devices.",
    "x86 architectures dominate PCs.",
    "RISC-V is an open instruction set.",
    "Custom silicon is becoming more common.",
    "Cloud providers design their own chips.",
    "Edge computing requires efficient chips.",
    "IoT devices prioritize low power.",
    "Battery life depends on chip efficiency.",
    "Energy harvesting powers some devices.",
    "Ultra-low-power design is critical for wearables.",
    "Medical devices rely on reliable chips.",
    "Implantable devices require strict standards.",
    "Semiconductor innovation continues to accelerate."
]